# -*- coding: utf-8 -*-
"""Spam Classifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6iQ5TxoGRIRZN_VIsDxr2X5oachAER-
"""

import pandas as pd
import nltk
import pickle
nltk.download('stopwords')
nltk.download('wordnet')
import re

df=pd.read_csv('spam', sep='\t', names=['Label', 'Messages'])
df.head()

df.shape

df.isnull().sum()

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()
corpus=[]
for i in range (0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['Messages'][i])
    review = review.lower()
    review = review.split()
    
    review = [wnl.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

corpus[1]

from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(max_features=2500)
x=cv.fit_transform(corpus).toarray()
y=pd.get_dummies(df['Label'])
y=y.iloc[:,1].values

pickle.dump(cv, open('tfidf.pkl', 'wb'))

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(x_train, y_train)

pickle.dump(clf, open('model.pkl', 'wb'))